#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="${1:-.tmp/tau-omp-worker-live-example}"
if [[ -z "${OMP_BIN:-}" ]]; then
  echo "OMP_BIN must point to an installed oh-my-pi/omp-compatible binary for live OMP sanity" >&2
  exit 2
fi

WORKSPACE_DIR="${OUT_DIR}/workspace"
REPO_DIR="${WORKSPACE_DIR}/repo"
RECEIPTS_DIR="${REPO_DIR}/.tau/receipts"
WORK_ORDER="${WORKSPACE_DIR}/work-order.json"
RESULT="${RECEIPTS_DIR}/omp-result.json"
RECEIPT="${RECEIPTS_DIR}/omp-worker-receipt.json"
LAUNCH_RECEIPT="${OUT_DIR}/omp-worker-launch-live-receipt.json"
DOCTOR_RECEIPT="${OUT_DIR}/omp-worker-doctor-live-receipt.json"
DEMO_RECEIPT="${OUT_DIR}/demo-receipt.json"
SANDBOX_RECEIPT="${RECEIPTS_DIR}/sandbox-run-receipt.json"

mkdir -p "${RECEIPTS_DIR}"
printf '# Tau live OMP worker schema probe\n\nDo not edit this file.\n' > "${REPO_DIR}/README.md"

python3 - "${WORK_ORDER}" "${SANDBOX_RECEIPT}" "${RESULT}" "${REPO_DIR}" <<'PY'
import hashlib
import json
import sys
from pathlib import Path

work_order_path = Path(sys.argv[1]).resolve()
sandbox_receipt_path = Path(sys.argv[2]).resolve()
result_path = Path(sys.argv[3]).resolve()
repo_dir = Path(sys.argv[4]).resolve()
goal_hash = "sha256:live-omp-worker-schema-probe-goal"
policy = {
    "schema": "tau.policy_profile.v1",
    "profile_id": "omp-live-probe-zero-trust",
    "default_decision": "deny",
    "requires_data_boundary": True,
    "network": {"default": "deny", "allowed_domains": []},
    "providers": {"cloud_llm": "deny", "local_model": "allow_with_approval"},
    "research": {
        "external_search": "deny",
        "manual_sanitized_receipt": "allow_with_review",
    },
    "memory": {"read": "allow", "write": "approval_required"},
    "github": {"public_mutation": "deny", "dry_run_projection": "allow"},
    "filesystem": {"write_allowlist": [".tau/receipts/**"], "read_denylist": ["secrets/**"]},
}
boundary = {
    "schema": "tau.data_boundary.v1",
    "classification": "public",
    "export_controlled": False,
    "itar": False,
    "technical_data": False,
    "foreign_person_access": "allowed",
    "external_provider_allowed": False,
    "external_research_allowed": False,
    "public_repo_allowed": False,
    "notes": ["live OMP RPC probe with public temp data only"],
}
work_order = {
    "schema": "tau.executor.omp.v1",
    "dag_id": "live-omp-worker-schema-probe",
    "node_id": "coder",
    "agent": "coder",
    "goal_hash": goal_hash,
    "attempt": 1,
    "repo": str(repo_dir),
    "allowed_paths": [".tau/receipts/**"],
    "forbidden_paths": ["secrets/**", "src/**", "tests/**", "README.md"],
    "task": (
        "Return a bounded response only. Do not edit files. Tau will validate a "
        "separate prewritten worker result artifact for this live OMP transport probe."
    ),
    "required_artifacts": [],
    "result_path": ".tau/receipts/omp-result.json",
    "receipt_path": ".tau/receipts/omp-worker-receipt.json",
    "execution_substrate": "docker-sandbox",
    "sandbox_receipt_path": ".tau/receipts/sandbox-run-receipt.json",
    "high_stakes": True,
    "zero_trust": True,
    "timeout_s": 120,
    "policy_profile": policy,
    "data_boundary": boundary,
    "model_provider_route": {"surface": "omp_rpc"},
}
work_order_path.parent.mkdir(parents=True, exist_ok=True)
work_order_path.write_text(json.dumps(work_order, indent=2, sort_keys=True) + "\n", encoding="utf-8")
work_order_sha = "sha256:" + hashlib.sha256(work_order_path.read_bytes()).hexdigest()
sandbox = {
    "schema": "tau.sandbox_run_receipt.v1",
    "ok": True,
    "status": "PASS",
    "mocked": False,
    "live": True,
    "provider_live": False,
    "goal_hash": goal_hash,
    "work_order_sha256": work_order_sha,
    "command_executed": True,
    "network_egress": "denied",
    "provider_access": "denied",
    "policy_profile": {"schema": "tau.policy_profile.v1"},
    "data_boundary": {"schema": "tau.data_boundary.v1"},
}
sandbox_receipt_path.write_text(json.dumps(sandbox, indent=2, sort_keys=True) + "\n", encoding="utf-8")
result = {
    "schema": "tau.omp_worker_result.v1",
    "status": "NEEDS_REVIEW",
    "goal_hash": goal_hash,
    "changed_files": [],
    "artifacts": [],
    "tests_run": [],
    "findings": [],
    "next_recommended_route": "reviewer",
}
result_path.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

write_blocked_demo() {
  local stage="$1"
  local exit_code="$2"
  python3 - "${DEMO_RECEIPT}" "${RECEIPT}" "${LAUNCH_RECEIPT}" "${DOCTOR_RECEIPT}" "${OMP_BIN}" "${stage}" "${exit_code}" <<'PY'
import json
import sys
from pathlib import Path

demo_path = Path(sys.argv[1])
receipt_path = Path(sys.argv[2])
launch_receipt_path = Path(sys.argv[3])
doctor_receipt_path = Path(sys.argv[4])
omp_bin = sys.argv[5]
stage = sys.argv[6]
exit_code = int(sys.argv[7])

def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return {"read_error": str(exc)}

receipt = read_json(receipt_path)
launch_receipt = read_json(launch_receipt_path)
doctor_receipt = read_json(doctor_receipt_path)
payload = {
    "schema": "tau.omp_worker_live_example_receipt.v1",
    "ok": False,
    "status": "BLOCKED",
    "mocked": False,
    "live": "mixed",
    "provider_live": False,
    "blocked_stage": stage,
    "blocked_exit_code": exit_code,
    "omp_bin": omp_bin,
    "omp_command_source": "env",
    "worker_result_source": "tau_probe_fixture",
    "worker_receipt_path": str(receipt_path),
    "worker_receipt_schema": receipt.get("schema"),
    "worker_receipt_status": receipt.get("status"),
    "worker_receipt_alert_codes": receipt.get("alert_codes", []),
    "doctor_receipt_path": str(doctor_receipt_path),
    "doctor_receipt_schema": doctor_receipt.get("schema"),
    "doctor_receipt_status": doctor_receipt.get("status"),
    "doctor_command_found": doctor_receipt.get("command_found"),
    "doctor_version_executed": doctor_receipt.get("version_executed"),
    "doctor_version_exit_code": doctor_receipt.get("version_exit_code"),
    "doctor_alert_codes": doctor_receipt.get("alert_codes", []),
    "doctor_command_path": doctor_receipt.get("command_path"),
    "launch_receipt_path": str(launch_receipt_path),
    "launch_receipt_schema": launch_receipt.get("schema"),
    "launch_receipt_status": launch_receipt.get("status"),
    "launch_receipt_alert_codes": launch_receipt.get("alert_codes", []),
    "apply_launch_process_executed": launch_receipt.get("process_executed"),
    "apply_launch_exit_code": launch_receipt.get("exit_code"),
    "apply_launch_stdout_path": launch_receipt.get("stdout_path"),
    "apply_launch_stdout_sha256": launch_receipt.get("stdout_sha256"),
    "apply_launch_stderr_path": launch_receipt.get("stderr_path"),
    "apply_launch_stderr_sha256": launch_receipt.get("stderr_sha256"),
    "apply_launch_stdout_jsonl_valid": launch_receipt.get("stdout_jsonl_valid"),
    "apply_launch_response_frame_count": launch_receipt.get("response_frame_count"),
    "apply_launch_response_schemas": launch_receipt.get("response_schemas", []),
    "apply_launch_log_artifacts": launch_receipt.get("log_artifacts", []),
    "proof_scope": {
        "proves": [
            "Tau attempted a live OMP-compatible worker probe.",
            "Tau recorded the stage that blocked before claiming live OMP worker readiness.",
        ],
        "does_not_prove": [
            "OMP performed live coding work.",
            "The worker is trustworthy.",
            "The code is semantically correct.",
            "Provider/model semantic quality.",
            "Full sandbox isolation.",
        ],
    },
}
demo_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY
}

set +e
uv run tau omp-worker-doctor \
  --out "${DOCTOR_RECEIPT}" \
  --omp-bin "${OMP_BIN}" \
  --timeout-s "${TAU_OMP_LIVE_TIMEOUT_S:-10}" \
  >"${OUT_DIR}/omp-worker-doctor-live.stdout.json"
doctor_exit=$?
set -e
if [[ "${doctor_exit}" -ne 0 ]]; then
  write_blocked_demo "omp-worker-doctor" "${doctor_exit}"
  cat "${DEMO_RECEIPT}"
  exit "${doctor_exit}"
fi

set +e
uv run tau omp-worker-launch \
  --work-order "${WORK_ORDER}" \
  --out "${LAUNCH_RECEIPT}" \
  --apply \
  --omp-bin "${OMP_BIN}" \
  --timeout-s "${TAU_OMP_LIVE_TIMEOUT_S:-60}" \
  >"${OUT_DIR}/omp-worker-launch-live.stdout.json"
launch_exit=$?
set -e
if [[ "${launch_exit}" -ne 0 ]]; then
  write_blocked_demo "omp-worker-launch" "${launch_exit}"
  cat "${DEMO_RECEIPT}"
  exit "${launch_exit}"
fi

set +e
uv run tau omp-worker-validate \
  --work-order "${WORK_ORDER}" \
  --result "${RESULT}" \
  --out "${RECEIPT}" \
  >"${OUT_DIR}/omp-worker-validate-live.stdout.json"
validate_exit=$?
set -e
if [[ "${validate_exit}" -ne 0 ]]; then
  write_blocked_demo "omp-worker-validate" "${validate_exit}"
  cat "${DEMO_RECEIPT}"
  exit "${validate_exit}"
fi

python3 - "${DEMO_RECEIPT}" "${RECEIPT}" "${LAUNCH_RECEIPT}" "${DOCTOR_RECEIPT}" "${OMP_BIN}" <<'PY'
import json
import sys
from pathlib import Path

demo_path = Path(sys.argv[1])
receipt_path = Path(sys.argv[2])
launch_receipt_path = Path(sys.argv[3])
doctor_receipt_path = Path(sys.argv[4])
omp_bin = sys.argv[5]
receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
launch_receipt = json.loads(launch_receipt_path.read_text(encoding="utf-8"))
doctor_receipt = json.loads(doctor_receipt_path.read_text(encoding="utf-8"))
ok = (
    receipt.get("ok") is True
    and launch_receipt.get("ok") is True
    and doctor_receipt.get("ok") is True
    and launch_receipt.get("process_executed") is True
)
payload = {
    "schema": "tau.omp_worker_live_example_receipt.v1",
    "ok": ok,
    "status": "PASS" if ok else "BLOCKED",
    "mocked": False,
    "live": "mixed",
    "provider_live": False,
    "omp_bin": omp_bin,
    "omp_command_source": "env",
    "worker_result_source": "tau_probe_fixture",
    "worker_receipt_path": str(receipt_path),
    "worker_receipt_schema": receipt.get("schema"),
    "worker_receipt_status": receipt.get("status"),
    "worker_receipt_alert_codes": receipt.get("alert_codes", []),
    "doctor_receipt_path": str(doctor_receipt_path),
    "doctor_receipt_schema": doctor_receipt.get("schema"),
    "doctor_receipt_status": doctor_receipt.get("status"),
    "doctor_command_found": doctor_receipt.get("command_found"),
    "doctor_version_executed": doctor_receipt.get("version_executed"),
    "doctor_version_exit_code": doctor_receipt.get("version_exit_code"),
    "doctor_command_path": doctor_receipt.get("command_path"),
    "launch_receipt_path": str(launch_receipt_path),
    "launch_receipt_schema": launch_receipt.get("schema"),
    "launch_receipt_status": launch_receipt.get("status"),
    "launch_receipt_alert_codes": launch_receipt.get("alert_codes", []),
    "apply_launch_process_executed": launch_receipt.get("process_executed"),
    "apply_launch_exit_code": launch_receipt.get("exit_code"),
    "apply_launch_stdout_path": launch_receipt.get("stdout_path"),
    "apply_launch_stdout_sha256": launch_receipt.get("stdout_sha256"),
    "apply_launch_stderr_path": launch_receipt.get("stderr_path"),
    "apply_launch_stderr_sha256": launch_receipt.get("stderr_sha256"),
    "apply_launch_stdout_jsonl_valid": launch_receipt.get("stdout_jsonl_valid"),
    "apply_launch_response_frame_count": launch_receipt.get("response_frame_count"),
    "apply_launch_response_schemas": launch_receipt.get("response_schemas", []),
    "apply_launch_log_artifacts": launch_receipt.get("log_artifacts", []),
    "proof_scope": {
        "proves": [
            "Tau ran a live OMP command identity probe through omp-worker-doctor.",
            "Tau invoked the configured OMP-compatible RPC command through omp-worker-launch.",
            "Tau validated a bounded OMP worker result artifact with omp-worker-validate.",
        ],
        "does_not_prove": [
            "OMP performed live coding work.",
            "The worker is trustworthy.",
            "The code is semantically correct.",
            "Provider/model semantic quality.",
            "Full sandbox isolation.",
        ],
    },
}
demo_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
if not ok:
    raise SystemExit(1)
PY

cat "${DEMO_RECEIPT}"
