#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="${1:-.tmp/tau-scillm-worker-live-example}"
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
WORKSPACE_DIR="${OUT_DIR}/workspace"
REPO_DIR="${WORKSPACE_DIR}/repo"
RECEIPTS_DIR="${REPO_DIR}/.tau/receipts"
WORK_ORDER="${WORKSPACE_DIR}/work-order.json"
RESULT="${RECEIPTS_DIR}/scillm-result.json"
RECEIPT="${RECEIPTS_DIR}/scillm-worker-receipt.json"
LAUNCH_RECEIPT="${OUT_DIR}/scillm-worker-launch-live-receipt.json"
DEMO_RECEIPT="${OUT_DIR}/demo-receipt.json"
SANDBOX_RECEIPT="${RECEIPTS_DIR}/sandbox-run-receipt.json"

mkdir -p "${RECEIPTS_DIR}"
printf '# Tau live SciLLM worker schema probe\n\nDo not edit this file.\n' > "${REPO_DIR}/README.md"

python3 - "${WORK_ORDER}" "${SANDBOX_RECEIPT}" "${REPO_DIR}" <<'PY'
import hashlib
import json
import sys
from pathlib import Path

work_order_path = Path(sys.argv[1]).resolve()
sandbox_receipt_path = Path(sys.argv[2]).resolve()
repo_dir = Path(sys.argv[3]).resolve()
policy = {
    "schema": "tau.policy_profile.v1",
    "profile_id": "scillm-live-probe-zero-trust",
    "default_decision": "deny",
    "requires_data_boundary": True,
    "network": {"default": "deny", "allowed_domains": []},
    "providers": {"cloud_llm": "deny", "local_model": "allow_with_approval"},
    "research": {
        "external_search": "deny",
        "manual_sanitized_receipt": "allow_with_review",
    },
    "memory": {"read": "allow", "write": "approval_required"},
    "github": {"public_mutation": "deny", "dry_run_projection": "allow"},
    "filesystem": {"write_allowlist": [".tau/receipts/**"], "read_denylist": ["secrets/**"]},
}
boundary = {
    "schema": "tau.data_boundary.v1",
    "classification": "public",
    "export_controlled": False,
    "itar": False,
    "technical_data": False,
    "foreign_person_access": "allowed",
    "external_provider_allowed": False,
    "external_research_allowed": False,
    "public_repo_allowed": False,
    "notes": ["live SciLLM worker probe with public temp data only"],
}
goal_hash = "sha256:live-scillm-worker-schema-probe-goal"
work_order = {
    "schema": "tau.executor.scillm_worker.v1",
    "dag_id": "live-scillm-worker-schema-probe",
    "node_id": "coder",
    "agent": "coder",
    "goal_hash": goal_hash,
    "attempt": 1,
    "repo": str(repo_dir),
    "allowed_paths": [".tau/receipts/**"],
    "forbidden_paths": ["secrets/**", "src/**", "tests/**", "README.md"],
    "task": (
        "Create exactly one JSON file at .tau/receipts/scillm-result.json. "
        "Do not edit any other file. The JSON root must have a top-level key "
        "named schema with value tau.scillm_worker_result.v1. Do not use "
        "$schema. It must also include status PASS, goal_hash "
        f"{goal_hash}, changed_files [], artifacts [], tests_run [], "
        "findings [], and next_recommended_route reviewer."
    ),
    "required_artifacts": [],
    "result_path": ".tau/receipts/scillm-result.json",
    "receipt_path": ".tau/receipts/scillm-worker-receipt.json",
    "execution_substrate": "docker-sandbox",
    "sandbox_receipt_path": ".tau/receipts/sandbox-run-receipt.json",
    "high_stakes": True,
    "zero_trust": True,
    "timeout_s": 120,
    "policy_profile": policy,
    "data_boundary": boundary,
    "model_provider_route": {
        "surface": "opencode_serve",
        "endpoint": "/v1/scillm/opencode/runs",
        "agent": "build",
        "skills": ["scillm"],
    },
}
work_order_path.parent.mkdir(parents=True, exist_ok=True)
work_order_path.write_text(json.dumps(work_order, indent=2, sort_keys=True) + "\n", encoding="utf-8")
work_order_sha = "sha256:" + hashlib.sha256(work_order_path.read_bytes()).hexdigest()
sandbox = {
    "schema": "tau.sandbox_run_receipt.v1",
    "ok": True,
    "status": "PASS",
    "mocked": False,
    "live": True,
    "provider_live": False,
    "goal_hash": goal_hash,
    "work_order_sha256": work_order_sha,
    "command_executed": True,
    "network_egress": "denied",
    "provider_access": "denied",
    "policy_profile": {"schema": "tau.policy_profile.v1"},
    "data_boundary": {"schema": "tau.data_boundary.v1"},
}
sandbox_receipt_path.write_text(json.dumps(sandbox, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

uv run tau scillm-worker-launch \
  --work-order "${WORK_ORDER}" \
  --out "${LAUNCH_RECEIPT}" \
  --apply \
  --request-timeout-s "${TAU_SCILLM_LIVE_REQUEST_TIMEOUT_S:-180}" \
  >"${OUT_DIR}/scillm-worker-launch-live.stdout.json"

uv run tau scillm-worker-validate \
  --work-order "${WORK_ORDER}" \
  --result "${RESULT}" \
  --out "${RECEIPT}" \
  >"${OUT_DIR}/scillm-worker-validate-live.stdout.json"

python3 - "${DEMO_RECEIPT}" "${RECEIPT}" "${LAUNCH_RECEIPT}" "${RESULT}" <<'PY'
import json
import sys
from pathlib import Path

demo_path = Path(sys.argv[1])
receipt_path = Path(sys.argv[2])
launch_receipt_path = Path(sys.argv[3])
result_path = Path(sys.argv[4])
receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
launch_receipt = json.loads(launch_receipt_path.read_text(encoding="utf-8"))
result = json.loads(result_path.read_text(encoding="utf-8"))
ok = (
    receipt.get("ok") is True
    and launch_receipt.get("ok") is True
    and result.get("schema") == "tau.scillm_worker_result.v1"
)
payload = {
    "schema": "tau.scillm_worker_live_example_receipt.v1",
    "ok": ok,
    "status": "PASS" if ok else "BLOCKED",
    "mocked": False,
    "live": True,
    "provider_live": False,
    "worker_result_schema": result.get("schema"),
    "worker_receipt_path": str(receipt_path),
    "worker_receipt_schema": receipt.get("schema"),
    "worker_receipt_status": receipt.get("status"),
    "worker_receipt_alert_codes": receipt.get("alert_codes", []),
    "launch_receipt_path": str(launch_receipt_path),
    "launch_receipt_schema": launch_receipt.get("schema"),
    "launch_receipt_status": launch_receipt.get("status"),
    "launch_receipt_alert_codes": launch_receipt.get("alert_codes", []),
    "launch_url": launch_receipt.get("url"),
    "launch_http_status": launch_receipt.get("http_status"),
    "launch_scillm_run_status": launch_receipt.get("scillm_run_status"),
    "launch_run_id": launch_receipt.get("run_id"),
    "launch_session_id": launch_receipt.get("session_id"),
    "launch_response_result_path": launch_receipt.get("response_result_path"),
    "launch_response_result_sha256": launch_receipt.get("response_result_sha256"),
    "model_provider_route": launch_receipt.get("model_provider_route", {}),
    "proof_scope": {
        "proves": [
            "Tau posted a bounded SciLLM OpenCode-serve worker request to the configured local SciLLM endpoint.",
            "The SciLLM response named the expected worker result artifact.",
            "Tau validated the live worker result through scillm-worker-validate.",
        ],
        "does_not_prove": [
            "The worker is trustworthy.",
            "The code is semantically correct.",
            "Provider/model semantic quality.",
            "Full sandbox isolation.",
        ],
    },
}
demo_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
if not ok:
    raise SystemExit(1)
PY

cat "${DEMO_RECEIPT}"
